# frozen_string_literal: true
source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'httparty'
gem 'json-schema'
gem 'jsonpath'
gem 'json'
gem 'pry'
gem 'rest-client'
gem 'nokogiri'
gem 'activesupport'
gem 'faker'
gem  'data_magic'
